# Generated by Django 4.0 on 2021-12-19 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('pixel', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pixel_type', models.CharField(choices=[('main', 'Freshman'), ('conversion', 'Sophomore')], max_length=20)),
                ('client_id', models.IntegerField()),
                ('client_email', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PixelPostData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pixel', models.CharField(max_length=16)),
                ('user', models.CharField(max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
