# Generated by Django 4.0 on 2021-12-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_api', '0004_alter_pixel_pixel_type_alter_pixelpostdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixelpostdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
