# Generated by Django 4.0 on 2021-12-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_api', '0005_alter_pixelpostdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixelpostdata',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
