# Generated by Django 4.0 on 2021-12-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_api', '0006_alter_pixelpostdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixelpostdata',
            name='user',
            field=models.CharField(max_length=250),
        ),
    ]
