# Generated by Django 4.0 on 2021-12-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_api', '0007_alter_pixelpostdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixelpostdata',
            name='page',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
