# Generated by Django 4.0 on 2021-12-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_api', '0009_pixelpostdata_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixelpostdata',
            name='ip',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
